# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_win_usr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1053, 762)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("#frame{\n"
"background-color: rgb(210, 201, 234);\n"
"border-top-right-radius: 24;\n"
"border-bottom-right-radius: 24;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMaximumSize(QtCore.QSize(64, 80))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/assets/logo.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VCR OSD Mono")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.frame_6)
        self.frame_4.setStyleSheet("QRadioButton:indicator{\n"
"    width: 0;\n"
"    height: 0;\n"
"}\n"
"QRadioButton{\n"
"color: white;\n"
"background-color: rgb(68, 29, 154);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 16;\n"
"padding-left: 12;\n"
"padding-right: 12;\n"
"    font: 500 16pt \"Roboto Medium\";\n"
"}\n"
"QPushButton{\n"
"color: white;\n"
"background-color: rgb(68, 29, 154);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 7;\n"
"padding-left: 12;\n"
"padding-right: 12;\n"
"    font: 500 16pt \"Roboto Medium\";\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QRadioButton:checked{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pb_to_send_report = QtWidgets.QRadioButton(self.frame_4)
        self.pb_to_send_report.setStyleSheet("QRadioButton:indicator{\n"
"    width: 0;\n"
"    height: 0;\n"
"}")
        self.pb_to_send_report.setObjectName("pb_to_send_report")
        self.verticalLayout_5.addWidget(self.pb_to_send_report)
        self.pb_to_send_event = QtWidgets.QRadioButton(self.frame_4)
        self.pb_to_send_event.setObjectName("pb_to_send_event")
        self.verticalLayout_5.addWidget(self.pb_to_send_event)
        self.pb_to_about = QtWidgets.QRadioButton(self.frame_4)
        self.pb_to_about.setObjectName("pb_to_about")
        self.verticalLayout_5.addWidget(self.pb_to_about)
        self.horizontalLayout_4.addWidget(self.frame_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 10)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pb_write_abount_error = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.pb_write_abount_error.setFont(font)
        self.pb_write_abount_error.setFlat(True)
        self.pb_write_abount_error.setObjectName("pb_write_abount_error")
        self.verticalLayout_3.addWidget(self.pb_write_abount_error)
        self.verticalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 2)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.user_frame = QtWidgets.QFrame(self.frame_2)
        self.user_frame.setStyleSheet("#user_frame {\n"
"    border-radius: 16;\n"
"    background-color: rgb(210, 201, 234);\n"
"}")
        self.user_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_frame.setObjectName("user_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.user_frame)
        self.horizontalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pb_change_account = QtWidgets.QPushButton(self.user_frame)
        self.pb_change_account.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: rgb(68, 29, 154);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 7;\n"
"padding-left: 12;\n"
"padding-right: 12;\n"
"    font: 500 16pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}")
        self.pb_change_account.setObjectName("pb_change_account")
        self.horizontalLayout_3.addWidget(self.pb_change_account, 0, QtCore.Qt.AlignLeft)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.lbl_username = QtWidgets.QLabel(self.user_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(22)
        self.lbl_username.setFont(font)
        self.lbl_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_username.setObjectName("lbl_username")
        self.horizontalLayout_3.addWidget(self.lbl_username)
        spacerItem5 = QtWidgets.QSpacerItem(64, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 4)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 4)
        self.horizontalLayout_3.setStretch(4, 1)
        self.verticalLayout_4.addWidget(self.user_frame)
        self.content_frame = QtWidgets.QFrame(self.frame_2)
        self.content_frame.setStyleSheet("#content_frame {\n"
"    background-color: rgb(210, 201, 234);\n"
"    border-radius: 16;\n"
"}")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout_11.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.report_frame = QtWidgets.QFrame(self.page)
        self.report_frame.setStyleSheet("#report_frame {    \n"
"    background-color: rgb(100, 114, 240);\n"
"    border-radius: 18;\n"
"}")
        self.report_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.report_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.report_frame.setObjectName("report_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.report_frame)
        self.verticalLayout_6.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.report_frame)
        self.frame_7.setStyleSheet("color: white;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setStyleSheet("font: 500 14pt \"Roboto\";")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5, 0, QtCore.Qt.AlignTop)
        self.lbl_date = QtWidgets.QLabel(self.frame_10)
        self.lbl_date.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_date.setStyleSheet("font: 87 12pt \"Roboto\";")
        self.lbl_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_date.setObjectName("lbl_date")
        self.verticalLayout_7.addWidget(self.lbl_date, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setStyleSheet("font: 500 14pt \"Roboto\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        self.label_4.setStyleSheet("font: 87 12pt \"Roboto\";")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.horizontalLayout_5.addWidget(self.frame_11, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.widget = QtWidgets.QWidget(self.report_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 2))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 2))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"margin-left: 24;\n"
"margin-right: 24;")
        self.widget.setObjectName("widget")
        self.verticalLayout_6.addWidget(self.widget)
        self.frame_15 = QtWidgets.QFrame(self.report_frame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_10.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_8 = QtWidgets.QFrame(self.frame_15)
        self.frame_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_8.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: rgb(100, 63, 176);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 10;\n"
"padding-left: 8;\n"
"padding-right: 8;\n"
"    font: 500 12pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"    font: 14pt \"Roboto\";\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setContentsMargins(0, 8, 8, 8)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_9.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_12)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.pb_download_form = QtWidgets.QPushButton(self.frame_12)
        self.pb_download_form.setObjectName("pb_download_form")
        self.horizontalLayout_9.addWidget(self.pb_download_form)
        self.verticalLayout_9.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_8.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.pb_clip_form = QtWidgets.QPushButton(self.frame_13)
        self.pb_clip_form.setObjectName("pb_clip_form")
        self.horizontalLayout_8.addWidget(self.pb_clip_form)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_8)
        self.frame_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.frame_14)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.pb_clip_doc = QtWidgets.QPushButton(self.frame_14)
        self.pb_clip_doc.setStyleSheet("padding-left: 16;\n"
"padding-right: 16;")
        self.pb_clip_doc.setObjectName("pb_clip_doc")
        self.horizontalLayout_7.addWidget(self.pb_clip_doc)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.horizontalLayout_10.addWidget(self.frame_8, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.frame_15)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.frame_9 = QtWidgets.QFrame(self.report_frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.pb_send_report = QtWidgets.QPushButton(self.frame_9)
        self.pb_send_report.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: rgb(100, 63, 176);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 7;\n"
"padding-left: 12;\n"
"padding-right: 12;\n"
"    font: 500 14pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}rgb(100, 63, 176)")
        self.pb_send_report.setObjectName("pb_send_report")
        self.horizontalLayout_6.addWidget(self.pb_send_report)
        self.verticalLayout_6.addWidget(self.frame_9, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(2, 3)
        self.verticalLayout_6.setStretch(3, 2)
        self.verticalLayout_6.setStretch(4, 1)
        self.verticalLayout_2.addWidget(self.report_frame)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.events_frame = QtWidgets.QFrame(self.page_2)
        self.events_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.events_frame.setStyleSheet("#events_frame{\n"
"background-color: rgb(100, 114, 240);\n"
"border-radius: 18;\n"
"}\n"
"QLabel{\n"
"color: white;\n"
"font: 12pt \"Roboto\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 2px solid rgb(68, 29, 154);\n"
"    padding: 6;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(68, 29, 154);\n"
"    border-radius: 8\n"
"}\n"
"QTextEdit{\n"
"    border: 2px solid rgb(68, 29, 154);\n"
"    padding: 6;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(68, 29, 154);\n"
"    border-radius: 8\n"
"}")
        self.events_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.events_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.events_frame.setObjectName("events_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.events_frame)
        self.verticalLayout_12.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_17 = QtWidgets.QFrame(self.events_frame)
        self.frame_17.setStyleSheet("")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_13.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.frame_17)
        self.label_10.setStyleSheet("font: 500 14pt \"Roboto\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_17)
        self.label_11.setStyleSheet("font: 12pt \"Roboto\";")
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.verticalLayout_12.addWidget(self.frame_17)
        self.widget_2 = QtWidgets.QWidget(self.events_frame)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 2))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_12.addWidget(self.widget_2)
        self.frame_18 = QtWidgets.QFrame(self.events_frame)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_14.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_16 = QtWidgets.QFrame(self.frame_18)
        self.frame_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_12.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.frame_16)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.le_event_name = QtWidgets.QLineEdit(self.frame_16)
        self.le_event_name.setObjectName("le_event_name")
        self.horizontalLayout_12.addWidget(self.le_event_name)
        self.verticalLayout_14.addWidget(self.frame_16)
        self.frame_24 = QtWidgets.QFrame(self.frame_18)
        self.frame_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_20.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_20.setSpacing(6)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_20 = QtWidgets.QFrame(self.frame_24)
        self.frame_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.frame_20)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.le_start_date = QtWidgets.QLineEdit(self.frame_20)
        self.le_start_date.setStyleSheet("font: 12pt \"Roboto\";")
        self.le_start_date.setObjectName("le_start_date")
        self.horizontalLayout_13.addWidget(self.le_start_date)
        self.label_14 = QtWidgets.QLabel(self.frame_20)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.le_end_date = QtWidgets.QLineEdit(self.frame_20)
        self.le_end_date.setStyleSheet("font: 12pt \"Roboto\";")
        self.le_end_date.setObjectName("le_end_date")
        self.horizontalLayout_13.addWidget(self.le_end_date)
        self.verticalLayout_20.addWidget(self.frame_20)
        self.label_19 = QtWidgets.QLabel(self.frame_24)
        self.label_19.setStyleSheet("font-size: 8pt")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_20.addWidget(self.label_19)
        self.verticalLayout_14.addWidget(self.frame_24, 0, QtCore.Qt.AlignLeft)
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_15.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.frame_21)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15)
        self.te_results = QtWidgets.QTextEdit(self.frame_21)
        self.te_results.setObjectName("te_results")
        self.verticalLayout_15.addWidget(self.te_results)
        self.verticalLayout_14.addWidget(self.frame_21)
        self.verticalLayout_12.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.events_frame)
        self.frame_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_11.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pb_send = QtWidgets.QPushButton(self.frame_19)
        self.pb_send.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: rgb(100, 63, 176);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 10;\n"
"padding-left: 12;\n"
"padding-right: 12;\n"
"    font: 500 16pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}rgb(100, 63, 176)")
        self.pb_send.setObjectName("pb_send")
        self.horizontalLayout_11.addWidget(self.pb_send)
        spacerItem8 = QtWidgets.QSpacerItem(487, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_12.addWidget(self.frame_19)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(2, 5)
        self.verticalLayout_12.setStretch(3, 1)
        self.verticalLayout_10.addWidget(self.events_frame)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("QLabel {\n"
"    font: 500 16pt \"Roboto\";\n"
"    color: white\n"
"}")
        self.page_3.setObjectName("page_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_16.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.about_frame = QtWidgets.QFrame(self.page_3)
        self.about_frame.setStyleSheet("#about_frame {\n"
"    border-radius: 18;\n"
"    background-color: rgb(100, 114, 240);\n"
"}")
        self.about_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_frame.setObjectName("about_frame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.about_frame)
        self.verticalLayout_17.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_22 = QtWidgets.QFrame(self.about_frame)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_18.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.frame_22)
        self.label_16.setStyleSheet("font: 500 24pt \"Roboto\";")
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_18.addWidget(self.label_16)
        self.verticalLayout_17.addWidget(self.frame_22)
        self.widget_3 = QtWidgets.QWidget(self.about_frame)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 2))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 2))
        self.widget_3.setStyleSheet("background-color: white;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_17.addWidget(self.widget_3)
        self.frame_23 = QtWidgets.QFrame(self.about_frame)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_19.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_19.setSpacing(16)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.frame_23)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_19.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.frame_23)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.verticalLayout_17.addWidget(self.frame_23, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(2, 10)
        self.verticalLayout_16.addWidget(self.about_frame)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_11.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.content_frame)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 8)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "B8 analitics"))
        self.pb_to_send_report.setText(_translate("Form", "Отправить отчет"))
        self.pb_to_send_event.setText(_translate("Form", "Сообщить о србытиях"))
        self.pb_to_about.setText(_translate("Form", "Об акселераторе"))
        self.pb_write_abount_error.setText(_translate("Form", "Сообщить об ошибке"))
        self.pb_change_account.setText(_translate("Form", "Сменить аккаунт"))
        self.lbl_username.setText(_translate("Form", "Иван иванов"))
        self.label_5.setText(_translate("Form", "Сроки ближайщего отчета"))
        self.lbl_date.setText(_translate("Form", "Date"))
        self.label_3.setText(_translate("Form", "Отправка отчета"))
        self.label_4.setText(_translate("Form", "Чтобы отправить отчет прикрепите заполненую анкету и подписанную версию отчета."))
        self.label_7.setText(_translate("Form", "Загрузить анкету для отчета"))
        self.pb_download_form.setText(_translate("Form", "Скачать форму"))
        self.label_8.setText(_translate("Form", "Прикрепить заполненую анкету "))
        self.pb_clip_form.setText(_translate("Form", "Прикрепить анкету"))
        self.label_9.setText(_translate("Form", "Прикрепить подписанный документ "))
        self.pb_clip_doc.setText(_translate("Form", "Прикрепить документ"))
        self.pb_send_report.setText(_translate("Form", "Отправить отчет"))
        self.label_10.setText(_translate("Form", "Недавние события"))
        self.label_11.setText(_translate("Form", "Напишите о произошедших событиях за последний месяц повлиявших на жизнь проекта"))
        self.label_12.setText(_translate("Form", "Название события: "))
        self.label_13.setText(_translate("Form", "Начало: "))
        self.le_start_date.setInputMask(_translate("Form", "00 - 00 - 0000"))
        self.le_start_date.setText(_translate("Form", " -  - "))
        self.le_start_date.setPlaceholderText(_translate("Form", "ДД:ММ:ГГГГ"))
        self.label_14.setText(_translate("Form", "Конец: "))
        self.le_end_date.setInputMask(_translate("Form", "00 - 00 - 0000"))
        self.le_end_date.setPlaceholderText(_translate("Form", "ДД:ММ:ГГГГ"))
        self.label_19.setText(_translate("Form", "формат: ДД:ММ:ГГГГ"))
        self.label_15.setText(_translate("Form", "Результаты события: "))
        self.pb_send.setText(_translate("Form", "Отправить"))
        self.label_16.setText(_translate("Form", "Самый северный акселератор инновационных проектов B8!"))
        self.label_17.setText(_translate("Form", "Акселератор В8 - это ускоренная программа развития стартапов,\n"
"включающая в себя менторскую, финансовую и образовательную поддержку."))
        self.label_18.setText(_translate("Form", "Данное приложение позволяет вам удобно и быстро присылать отчетность о вашей работе, что позволяет акселератору узнать о вам больше и в последствии больше помогать вашему проекту."))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
