# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_win_adm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1053, 762)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("#frame{\n"
"background-color: rgb(210, 201, 234);\n"
"border-top-right-radius: 24;\n"
"border-bottom-right-radius: 24;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMaximumSize(QtCore.QSize(64, 80))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/assets/logo.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VCR OSD Mono")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.frame_6)
        self.frame_4.setStyleSheet("QRadioButton:indicator{\n"
"    width: 0;\n"
"    height: 0;\n"
"}\n"
"QRadioButton{\n"
"color: white;\n"
"background-color: rgb(68, 29, 154);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 12;\n"
"padding-left: 12;\n"
"padding-right: 12;\n"
"    font: 500 16pt \"Roboto Medium\";\n"
"}\n"
"QPushButton{\n"
"color: white;\n"
"background-color: rgb(68, 29, 154);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 7;\n"
"padding-left: 12;\n"
"padding-right: 12;\n"
"    font: 500 16pt \"Roboto Medium\";\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QRadioButton:checked{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pb_to_ready_reports = QtWidgets.QRadioButton(self.frame_4)
        self.pb_to_ready_reports.setStyleSheet("QRadioButton:indicator{\n"
"    width: 0;\n"
"    height: 0;\n"
"}")
        self.pb_to_ready_reports.setObjectName("pb_to_ready_reports")
        self.verticalLayout_5.addWidget(self.pb_to_ready_reports)
        self.pb_to_all_reports = QtWidgets.QRadioButton(self.frame_4)
        self.pb_to_all_reports.setObjectName("pb_to_all_reports")
        self.verticalLayout_5.addWidget(self.pb_to_all_reports)
        self.pb_to_create_account = QtWidgets.QRadioButton(self.frame_4)
        self.pb_to_create_account.setObjectName("pb_to_create_account")
        self.verticalLayout_5.addWidget(self.pb_to_create_account)
        self.pb_to_accounts = QtWidgets.QRadioButton(self.frame_4)
        self.pb_to_accounts.setObjectName("pb_to_accounts")
        self.verticalLayout_5.addWidget(self.pb_to_accounts)
        self.horizontalLayout_4.addWidget(self.frame_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 10)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pb_write_abount_error = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.pb_write_abount_error.setFont(font)
        self.pb_write_abount_error.setFlat(True)
        self.pb_write_abount_error.setObjectName("pb_write_abount_error")
        self.verticalLayout_3.addWidget(self.pb_write_abount_error)
        self.verticalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 2)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.user_frame = QtWidgets.QFrame(self.frame_2)
        self.user_frame.setStyleSheet("#user_frame {\n"
"    border-radius: 16;\n"
"    background-color: rgb(210, 201, 234);\n"
"}")
        self.user_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_frame.setObjectName("user_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.user_frame)
        self.horizontalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pb_change_account = QtWidgets.QPushButton(self.user_frame)
        self.pb_change_account.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: rgb(68, 29, 154);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 7;\n"
"padding-left: 12;\n"
"padding-right: 12;\n"
"    font: 500 16pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}")
        self.pb_change_account.setObjectName("pb_change_account")
        self.horizontalLayout_3.addWidget(self.pb_change_account, 0, QtCore.Qt.AlignLeft)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.lbl_username = QtWidgets.QLabel(self.user_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(22)
        self.lbl_username.setFont(font)
        self.lbl_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_username.setObjectName("lbl_username")
        self.horizontalLayout_3.addWidget(self.lbl_username)
        spacerItem5 = QtWidgets.QSpacerItem(64, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 4)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 4)
        self.horizontalLayout_3.setStretch(4, 1)
        self.verticalLayout_4.addWidget(self.user_frame)
        self.content_frame = QtWidgets.QFrame(self.frame_2)
        self.content_frame.setStyleSheet("#content_frame {\n"
"    background-color: rgb(210, 201, 234);\n"
"    border-radius: 16;\n"
"}")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout_11.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_frame)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.stackedWidget.setStyleSheet("#stackedWidget {\n"
"    background-color: rgb(210, 201, 234);\n"
"}")
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ready_page = QtWidgets.QWidget()
        self.ready_page.setStyleSheet("border-bottom-left: 12;\n"
"border-bottom-right: 12;")
        self.ready_page.setObjectName("ready_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ready_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 8)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ready_header_frame = QtWidgets.QFrame(self.ready_page)
        self.ready_header_frame.setStyleSheet("#ready_header_frame{\n"
"background-color: rgb(68, 29, 154);\n"
"border-top-right-radius: 12;\n"
"border-top-left-radius: 12;\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"    font: 14pt \"Roboto\";\n"
"}")
        self.ready_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ready_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ready_header_frame.setObjectName("ready_header_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ready_header_frame)
        self.horizontalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.ready_header_frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6, 0, QtCore.Qt.AlignBottom)
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setStyleSheet("font: 300 10pt \"Roboto Light\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.horizontalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignTop)
        self.frame_9 = QtWidgets.QFrame(self.ready_header_frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.frame_9, 0, QtCore.Qt.AlignTop)
        self.frame_10 = QtWidgets.QFrame(self.ready_header_frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pb_find_all = QtWidgets.QPushButton(self.frame_11)
        self.pb_find_all.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/icons/search_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_find_all.setIcon(icon)
        self.pb_find_all.setIconSize(QtCore.QSize(24, 24))
        self.pb_find_all.setAutoDefault(False)
        self.pb_find_all.setDefault(False)
        self.pb_find_all.setFlat(True)
        self.pb_find_all.setObjectName("pb_find_all")
        self.horizontalLayout_6.addWidget(self.pb_find_all)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    font: 500 12pt \"Roboto\";\n"
"    background-color: rgb(68, 29, 154);\n"
"    border: 3px solid rgb(210, 201, 234);\n"
"    padding: 6;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8\n"
"}")
        self.lineEdit.setFrame(True)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 10)
        self.verticalLayout_9.addWidget(self.frame_11)
        self.horizontalLayout_5.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_6.addWidget(self.ready_header_frame)
        self.scrollArea = QtWidgets.QScrollArea(self.ready_page)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setStyleSheet("#scrollArea{\n"
"border-bottom-right-radius: 12;\n"
"border-bottom-left-radius: 12;\n"
"background-color: white;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 83, 16))
        self.widget.setStyleSheet("border-bottom-right-radius: 12;\n"
"border-bottom-left-radius: 12;")
        self.widget.setObjectName("widget")
        self.vl_ready = QtWidgets.QVBoxLayout(self.widget)
        self.vl_ready.setContentsMargins(8, 8, 8, 8)
        self.vl_ready.setSpacing(0)
        self.vl_ready.setObjectName("vl_ready")
        self.scrollArea.setWidget(self.widget)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.ready_page)
        self.all_page = QtWidgets.QWidget()
        self.all_page.setObjectName("all_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.all_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.all_header_frame = QtWidgets.QFrame(self.all_page)
        self.all_header_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.all_header_frame.setStyleSheet("#all_header_frame{\n"
"background-color: rgb(68, 29, 154);\n"
"border-top-right-radius: 12;\n"
"border-top-left-radius: 12;\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"    font: 14pt \"Roboto\";\n"
"}")
        self.all_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.all_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.all_header_frame.setObjectName("all_header_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.all_header_frame)
        self.horizontalLayout_7.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.all_header_frame)
        self.frame_12.setStyleSheet("QCheckBox::indicatror {\n"
"    width: 24;\n"
"    height: 24;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    color: rgb(210, 201, 234);\n"
"}\n"
"QCheckBox { \n"
"    color: white;\n"
"    \n"
"    font: 14pt \"Roboto\";\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked { \n"
"    \n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_10.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.frame_12)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8, 0, QtCore.Qt.AlignBottom)
        self.frame_16 = QtWidgets.QFrame(self.frame_12)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_10.setContentsMargins(0, 8, 8, 8)
        self.horizontalLayout_10.setSpacing(16)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.chbox_sended = QtWidgets.QCheckBox(self.frame_16)
        self.chbox_sended.setChecked(True)
        self.chbox_sended.setObjectName("chbox_sended")
        self.horizontalLayout_10.addWidget(self.chbox_sended)
        self.chbox_wait = QtWidgets.QCheckBox(self.frame_16)
        self.chbox_wait.setChecked(True)
        self.chbox_wait.setObjectName("chbox_wait")
        self.horizontalLayout_10.addWidget(self.chbox_wait)
        self.verticalLayout_10.addWidget(self.frame_16, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.setStretch(0, 1)
        self.horizontalLayout_7.addWidget(self.frame_12, 0, QtCore.Qt.AlignTop)
        self.frame_14 = QtWidgets.QFrame(self.all_header_frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_12.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame_14)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_12.setAutoDefault(False)
        self.pushButton_12.setDefault(False)
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_8.addWidget(self.pushButton_12)
        self.le_find_all = QtWidgets.QLineEdit(self.frame_15)
        self.le_find_all.setStyleSheet("QLineEdit{\n"
"    font: 500 12pt \"Roboto\";\n"
"    background-color: rgb(68, 29, 154);\n"
"    border: 3px solid rgb(210, 201, 234);\n"
"    padding: 6;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8\n"
"}")
        self.le_find_all.setFrame(True)
        self.le_find_all.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.le_find_all.setClearButtonEnabled(False)
        self.le_find_all.setObjectName("le_find_all")
        self.horizontalLayout_8.addWidget(self.le_find_all)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 10)
        self.verticalLayout_12.addWidget(self.frame_15)
        self.horizontalLayout_7.addWidget(self.frame_14, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.all_header_frame)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.all_page)
        self.scrollArea_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea_2.setStyleSheet("#scrollArea_2{\n"
"border-bottom-right-radius: 12;\n"
"border-bottom-left-radius: 12;\n"
"background-color: white;\n"
"}")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setLineWidth(0)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.widget_2 = QtWidgets.QWidget()
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.widget_2.setStyleSheet("border-bottom-right-radius: 12;\n"
"border-bottom-left-radius: 12;")
        self.widget_2.setObjectName("widget_2")
        self.vl_all = QtWidgets.QVBoxLayout(self.widget_2)
        self.vl_all.setContentsMargins(0, 0, 0, 0)
        self.vl_all.setSpacing(6)
        self.vl_all.setObjectName("vl_all")
        self.scrollArea_2.setWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)
        self.stackedWidget.addWidget(self.all_page)
        self.create_page = QtWidgets.QWidget()
        self.create_page.setObjectName("create_page")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.create_page)
        self.verticalLayout_16.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.account_frame = QtWidgets.QFrame(self.create_page)
        self.account_frame.setStyleSheet("#account_frame { \n"
"    border-radius: 18;\n"
"    background-color: rgb(68, 29, 154);\n"
"}\n"
"QLineEdit{\n"
"    font: 500 14pt \"Roboto\";\n"
"    background-color: rgb(68, 29, 154);\n"
"    border: 2px solid rgb(210, 201, 234);\n"
"    padding: 6;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8\n"
"}")
        self.account_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.account_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.account_frame.setObjectName("account_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.account_frame)
        self.verticalLayout_14.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_17 = QtWidgets.QFrame(self.account_frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.frame_17)
        self.label_9.setStyleSheet("font: 500 18pt \"Roboto Medium\";\n"
"color: white;\n"
"")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_17)
        self.label_10.setStyleSheet("color: white;\n"
"font: 14pt \"Roboto\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.verticalLayout_14.addWidget(self.frame_17, 0, QtCore.Qt.AlignTop)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem6)
        self.frame_8 = QtWidgets.QFrame(self.account_frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_11.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem7 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.frame_18 = QtWidgets.QFrame(self.frame_8)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_15.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.le_name = QtWidgets.QLineEdit(self.frame_18)
        self.le_name.setObjectName("le_name")
        self.verticalLayout_15.addWidget(self.le_name)
        self.le_surname = QtWidgets.QLineEdit(self.frame_18)
        self.le_surname.setObjectName("le_surname")
        self.verticalLayout_15.addWidget(self.le_surname)
        self.le_login = QtWidgets.QLineEdit(self.frame_18)
        self.le_login.setObjectName("le_login")
        self.verticalLayout_15.addWidget(self.le_login)
        self.le_password = QtWidgets.QLineEdit(self.frame_18)
        self.le_password.setObjectName("le_password")
        self.verticalLayout_15.addWidget(self.le_password)
        self.pb_add_logo = QtWidgets.QPushButton(self.frame_18)
        self.pb_add_logo.setStyleSheet("\n"
"QPushButton{\n"
"margin-top: 8;\n"
"color: white;\n"
"    background-color: rgb(78, 34, 181);\n"
"border: 2px solid rgb(210, 201, 234);\n"
"border-radius: 12;\n"
"padding: 7;\n"
"    font: 500 12pt \"Roboto Medium\";\n"
"padding-top: 10;\n"
"padding-bottom: 10;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}")
        self.pb_add_logo.setObjectName("pb_add_logo")
        self.verticalLayout_15.addWidget(self.pb_add_logo)
        self.horizontalLayout_11.addWidget(self.frame_18)
        spacerItem8 = QtWidgets.QSpacerItem(59, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 8)
        self.horizontalLayout_11.setStretch(2, 1)
        self.verticalLayout_14.addWidget(self.frame_8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem9)
        self.frame_13 = QtWidgets.QFrame(self.account_frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.pb_create_account = QtWidgets.QPushButton(self.frame_13)
        self.pb_create_account.setStyleSheet("QPushButton{\n"
"color: white;\n"
"    background-color: rgb(78, 34, 181);\n"
"border: 2px solid rgb(210, 201, 234);\n"
"border-radius: 18;\n"
"padding: 7;\n"
"    font: 500 12pt \"Roboto Medium\";\n"
"padding-top: 10;\n"
"padding-bottom: 10;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}")
        self.pb_create_account.setObjectName("pb_create_account")
        self.horizontalLayout_9.addWidget(self.pb_create_account)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 5)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_14.addWidget(self.frame_13)
        self.verticalLayout_14.setStretch(0, 2)
        self.verticalLayout_14.setStretch(1, 1)
        self.verticalLayout_14.setStretch(2, 5)
        self.verticalLayout_14.setStretch(3, 1)
        self.verticalLayout_14.setStretch(4, 2)
        self.verticalLayout_16.addWidget(self.account_frame)
        self.stackedWidget.addWidget(self.create_page)
        self.accounts_page = QtWidgets.QWidget()
        self.accounts_page.setObjectName("accounts_page")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.accounts_page)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.accounts_header_frame = QtWidgets.QFrame(self.accounts_page)
        self.accounts_header_frame.setMaximumSize(QtCore.QSize(16777215, 2345))
        self.accounts_header_frame.setStyleSheet("#accounts_header_frame{\n"
"background-color: rgb(68, 29, 154);\n"
"border-top-right-radius: 12;\n"
"border-top-left-radius: 12;\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"    font: 14pt \"Roboto\";\n"
"}")
        self.accounts_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accounts_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accounts_header_frame.setObjectName("accounts_header_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.accounts_header_frame)
        self.horizontalLayout_12.setContentsMargins(11, 8, 8, 8)
        self.horizontalLayout_12.setSpacing(8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_19 = QtWidgets.QFrame(self.accounts_header_frame)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_17.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.frame_19)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_17.addWidget(self.label_12, 0, QtCore.Qt.AlignBottom)
        self.label_13 = QtWidgets.QLabel(self.frame_19)
        self.label_13.setStyleSheet("font: 300 10pt \"Roboto Light\";")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_17.addWidget(self.label_13, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(1, 1)
        self.horizontalLayout_12.addWidget(self.frame_19, 0, QtCore.Qt.AlignTop)
        self.frame_23 = QtWidgets.QFrame(self.accounts_header_frame)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_21.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_21.setSpacing(6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_16 = QtWidgets.QLabel(self.frame_23)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_21.addWidget(self.label_16, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_12.addWidget(self.frame_23)
        self.frame_20 = QtWidgets.QFrame(self.accounts_header_frame)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_18.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.frame_20)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_18.addWidget(self.label_14, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_12.addWidget(self.frame_20, 0, QtCore.Qt.AlignTop)
        self.frame_21 = QtWidgets.QFrame(self.accounts_header_frame)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_19.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.frame_21)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_19.addWidget(self.label_15)
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pb_find_ready = QtWidgets.QPushButton(self.frame_22)
        self.pb_find_ready.setText("")
        self.pb_find_ready.setIcon(icon)
        self.pb_find_ready.setIconSize(QtCore.QSize(24, 24))
        self.pb_find_ready.setAutoDefault(False)
        self.pb_find_ready.setDefault(False)
        self.pb_find_ready.setFlat(True)
        self.pb_find_ready.setObjectName("pb_find_ready")
        self.horizontalLayout_13.addWidget(self.pb_find_ready)
        self.le_find_ready = QtWidgets.QLineEdit(self.frame_22)
        self.le_find_ready.setStyleSheet("QLineEdit{\n"
"    font: 500 12pt \"Roboto\";\n"
"    background-color: rgb(68, 29, 154);\n"
"    border: 3px solid rgb(210, 201, 234);\n"
"    padding: 6;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8\n"
"}")
        self.le_find_ready.setFrame(True)
        self.le_find_ready.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.le_find_ready.setClearButtonEnabled(False)
        self.le_find_ready.setObjectName("le_find_ready")
        self.horizontalLayout_13.addWidget(self.le_find_ready)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 10)
        self.verticalLayout_19.addWidget(self.frame_22)
        self.horizontalLayout_12.addWidget(self.frame_21, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_12.setStretch(2, 1)
        self.horizontalLayout_12.setStretch(3, 1)
        self.verticalLayout_20.addWidget(self.accounts_header_frame)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.accounts_page)
        self.scrollArea_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea_3.setStyleSheet("#widget_3, #scrollArea_3 {\n"
"    background-color: white;\n"
"    border-bottom-left-radius: 12;\n"
"    border-bottom-right-radius: 12;\n"
"}\n"
"")
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.widget_3 = QtWidgets.QWidget()
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 707, 513))
        self.widget_3.setObjectName("widget_3")
        self.vl_accounts = QtWidgets.QVBoxLayout(self.widget_3)
        self.vl_accounts.setContentsMargins(8, 8, 8, 8)
        self.vl_accounts.setSpacing(6)
        self.vl_accounts.setObjectName("vl_accounts")
        self.scrollArea_3.setWidget(self.widget_3)
        self.verticalLayout_20.addWidget(self.scrollArea_3)
        self.stackedWidget.addWidget(self.accounts_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setStyleSheet("font: 75 36pt \"Roboto\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout_11.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.content_frame)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 8)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "B8 analitics"))
        self.pb_to_ready_reports.setText(_translate("Form", "Готовые отчеты"))
        self.pb_to_all_reports.setText(_translate("Form", "Все отчеты"))
        self.pb_to_create_account.setText(_translate("Form", "Создать аккаунт"))
        self.pb_to_accounts.setText(_translate("Form", "Список аккаунтов"))
        self.pb_write_abount_error.setText(_translate("Form", "Сообщить об ошибке"))
        self.pb_change_account.setText(_translate("Form", "Сменить аккаунт"))
        self.lbl_username.setText(_translate("Form", "Administrator"))
        self.label_6.setText(_translate("Form", "Получить отчет"))
        self.label_7.setText(_translate("Form", "Выберите формат отчета"))
        self.label_5.setText(_translate("Form", "Дата отправки"))
        self.label_4.setText(_translate("Form", "Название компании"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Найти компанию"))
        self.label_8.setText(_translate("Form", "Состояние отчета"))
        self.chbox_sended.setText(_translate("Form", "Отправлено"))
        self.chbox_wait.setText(_translate("Form", "В ожидании"))
        self.label_11.setText(_translate("Form", "Название компании"))
        self.le_find_all.setPlaceholderText(_translate("Form", "Найти компанию"))
        self.label_9.setText(_translate("Form", "Cоздание аккаунта"))
        self.label_10.setText(_translate("Form", "Заполните форму ниже\n"
"После создания аккаунта, он появится в списке аккаунтов"))
        self.le_name.setPlaceholderText(_translate("Form", "Имя"))
        self.le_surname.setPlaceholderText(_translate("Form", "Фамилия"))
        self.le_login.setPlaceholderText(_translate("Form", "Логин"))
        self.le_password.setPlaceholderText(_translate("Form", "Пароль"))
        self.pb_add_logo.setText(_translate("Form", "Прикрепить лого"))
        self.pb_create_account.setText(_translate("Form", "Создать аккаунт"))
        self.label_12.setText(_translate("Form", "Логин / Пароль"))
        self.label_16.setText(_translate("Form", "Лого"))
        self.label_14.setText(_translate("Form", "Фамилия, Имя"))
        self.label_15.setText(_translate("Form", "Название компании"))
        self.le_find_ready.setPlaceholderText(_translate("Form", "Найти компанию"))
        self.label_3.setText(_translate("Form", "Самый северный акселератор инновационных проектов B8!"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
