# Form implementation generated from reading ui file '.\report_row.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(786, 59)
        Form.setStyleSheet("#Form {\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"}\n"
"QLabel{\n"
"    color: rgb(68, 29, 154);\n"
"    font: 14pt \"Roboto\";\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(parent=self.frame)
        self.lbl_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_date = QtWidgets.QLabel(parent=self.frame_2)
        self.lbl_date.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_date.setObjectName("lbl_date")
        self.verticalLayout_2.addWidget(self.lbl_date)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=Form)
        self.frame_3.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: rgb(100, 63, 176);\n"
"border: none;\n"
"border-radius: 16;\n"
"padding: 7;\n"
"padding-left: 12;\n"
"padding-right: 12;\n"
"    font: 500 16pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(115, 74, 206);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    color: rgb(68, 29, 154);\n"
"    background-color: white;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_excel = QtWidgets.QPushButton(parent=self.frame_3)
        self.pb_excel.setObjectName("pb_excel")
        self.horizontalLayout_2.addWidget(self.pb_excel)
        spacerItem = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pb_pdf = QtWidgets.QPushButton(parent=self.frame_3)
        self.pb_pdf.setObjectName("pb_pdf")
        self.horizontalLayout_2.addWidget(self.pb_pdf)
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_name.setText(_translate("Form", "Name"))
        self.lbl_date.setText(_translate("Form", "Date"))
        self.pb_excel.setText(_translate("Form", "XLSX"))
        self.pb_pdf.setText(_translate("Form", "PDF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
